package org.beeblos.bpm.core.model.thin;

import java.util.Date;

import org.beeblos.bpm.core.model.WEmailAccount;
import org.beeblos.bpm.core.model.WEmailTemplates;
import org.beeblos.bpm.core.model.WProcessHead;
import org.beeblos.bpm.core.model.WTimeUnit;


/**
 * WProcessDef generated by hbm2java
 */
public class WProcessDefThin implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;

	private Integer version;
	
	private WProcessHead processHead;
	
	private boolean active;
	
	private Date productionDate;
	private Integer productionUser;
	
	private String comments;
	
	private Integer beginStepId;
	
	private String listZoneId; // pag que define la lista de seleccion de steps
	private String workZoneId; // pag que define la zona de trabajo
	private String additionalZoneId; // pag que define la zona de ayuda ( info adicional )
	
	private String processorStepId; // dml 20120619

	// dml 20120105
	private String adminEmail;

	private Integer totalTime;
	private WTimeUnit totalTimeUnit;
	private String globalDeadlineDate;
		
	private Date insertDate;
	private Integer insertUser;
	private Date modDate;
	private Integer modUser;
	
//	private ManagedData managedDataDef;
	
	/**
	 * TODO quitar esto de aquí y ver una opcion mas generalizada de gestion de los avisos
	 * 
	 * (digo que esto hay que quitarlo de aquí para descargar un poco el objeto ... pero por
	 * ahi es conveniente que esté, depende de como encaremos la solución de mensajería ...)
	 * 
	 */

	private WEmailAccount systemEmailAccount;
	private WEmailTemplates arrivingAdminNoticeTemplate;
	private WEmailTemplates arrivingUserNoticeTemplate;	

	public WProcessDefThin() {
		super();
	}

	public WProcessDefThin(WProcessDefThin pdth) {
		this.id = pdth.getId();
		this.version = pdth.getVersion();
		this.processHead = pdth.getProcessHead();
		this.active = pdth.isActive();
		this.productionDate = pdth.getProductionDate();
		this.productionUser = pdth.getProductionUser();
		this.comments = pdth.getComments();
		this.beginStepId = pdth.getBeginStepId();
		this.listZoneId = pdth.getListZoneId();
		this.workZoneId =pdth.getWorkZoneId();
		this.additionalZoneId = pdth.getAdditionalZoneId();
		this.processorStepId = pdth.getProcessorStepId();
		this.adminEmail = pdth.getAdminEmail();
		this.totalTime = pdth.getTotalTime();
		this.totalTimeUnit = pdth.getTotalTimeUnit();
		this.globalDeadlineDate = pdth.getGlobalDeadlineDate();
		this.insertDate = pdth.getInsertDate();
		this.insertUser = pdth.getInsertUser();
		this.modDate = pdth.getModDate();
		this.modUser = pdth.getModUser();
		this.systemEmailAccount = pdth.getSystemEmailAccount();
		this.arrivingAdminNoticeTemplate = pdth.getArrivingAdminNoticeTemplate();
		this.arrivingUserNoticeTemplate = pdth.getArrivingUserNoticeTemplate();
	}
	
	public WProcessDefThin(Integer id, WProcessHead processHead,
			boolean active, Date productionDate,
			Integer productionUser, String comments, Integer beginStepId,
			String listZoneId, String workZoneId, String additionalZoneId,
			String processorStepId, String adminEmail, Integer totalTime,
			WTimeUnit totalTimeUnit, String globalDeadlineDate,
			Date insertDate, Integer insertUser, Date modDate, Integer modUser,
			WEmailAccount systemEmailAccount,
			WEmailTemplates arrivingAdminNoticeTemplate,
			WEmailTemplates arrivingUserNoticeTemplate) {
		this.id = id;
		this.processHead = processHead;
		this.active = active;
		this.productionDate = productionDate;
		this.productionUser = productionUser;
		this.comments = comments;
		this.beginStepId = beginStepId;
		this.listZoneId = listZoneId;
		this.workZoneId = workZoneId;
		this.additionalZoneId = additionalZoneId;
		this.processorStepId = processorStepId;
		this.adminEmail = adminEmail;
		this.totalTime = totalTime;
		this.totalTimeUnit = totalTimeUnit;
		this.globalDeadlineDate = globalDeadlineDate;
		this.insertDate = insertDate;
		this.insertUser = insertUser;
		this.modDate = modDate;
		this.modUser = modUser;
		this.systemEmailAccount = systemEmailAccount;
		this.arrivingAdminNoticeTemplate = arrivingAdminNoticeTemplate;
		this.arrivingUserNoticeTemplate = arrivingUserNoticeTemplate;
	}


	public WProcessDefThin(boolean createEmtpyObjects ){
		super();
		if ( createEmtpyObjects ) {

			
		}	
	}

	/**
	 * convenience method to return process name (processDef=version has it's name in processHead)
	 * 
	 * @return
	 */
	public String getName() {
		return processHead.getName();
	}


	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public WProcessHead getProcessHead() {
		return processHead;
	}

	public void setProcessHead(WProcessHead processHead) {
		this.processHead = processHead;
	}

	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Date getProductionDate() {
		return productionDate;
	}

	public void setProductionDate(Date productionDate) {
		this.productionDate = productionDate;
	}

	public Integer getProductionUser() {
		return productionUser;
	}


	public void setProductionUser(Integer productionUser) {
		this.productionUser = productionUser;
	}


	public String getComments() {
		return comments;
	}


	public void setComments(String comments) {
		this.comments = comments;
	}


	public Integer getBeginStepId() {
		return beginStepId;
	}


	public void setBeginStepId(Integer beginStepId) {
		this.beginStepId = beginStepId;
	}

	public String getListZoneId() {
		return listZoneId;
	}


	public void setListZoneId(String listZoneId) {
		this.listZoneId = listZoneId;
	}


	public String getWorkZoneId() {
		return workZoneId;
	}


	public void setWorkZoneId(String workZoneId) {
		this.workZoneId = workZoneId;
	}


	public String getAdditionalZoneId() {
		return additionalZoneId;
	}


	public void setAdditionalZoneId(String additionalZoneId) {
		this.additionalZoneId = additionalZoneId;
	}


	public String getProcessorStepId() {
		return processorStepId;
	}


	public void setProcessorStepId(String processorStepId) {
		this.processorStepId = processorStepId;
	}


	public String getAdminEmail() {
		return adminEmail;
	}


	public void setAdminEmail(String adminEmail) {
		this.adminEmail = adminEmail;
	}


	public Integer getTotalTime() {
		return totalTime;
	}


	public void setTotalTime(Integer totalTime) {
		this.totalTime = totalTime;
	}


	public WTimeUnit getTotalTimeUnit() {
		return totalTimeUnit;
	}


	public void setTotalTimeUnit(WTimeUnit totalTimeUnit) {
		this.totalTimeUnit = totalTimeUnit;
	}


	public String getGlobalDeadlineDate() {
		return globalDeadlineDate;
	}


	public void setGlobalDeadlineDate(String globalDeadlineDate) {
		this.globalDeadlineDate = globalDeadlineDate;
	}


	public Date getInsertDate() {
		return insertDate;
	}


	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}


	public Integer getInsertUser() {
		return insertUser;
	}


	public void setInsertUser(Integer insertUser) {
		this.insertUser = insertUser;
	}


	public Date getModDate() {
		return modDate;
	}


	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}


	public Integer getModUser() {
		return modUser;
	}


	public void setModUser(Integer modUser) {
		this.modUser = modUser;
	}


//	public ManagedData getManagedDataDef() {
//		return managedDataDef;
//	}

//
//	public void setManagedDataDef(ManagedData managedDataDef) {
//		this.managedDataDef = managedDataDef;
//	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (active ? 1231 : 1237);
		result = prime
				* result
				+ ((additionalZoneId == null) ? 0 : additionalZoneId.hashCode());
		result = prime * result
				+ ((adminEmail == null) ? 0 : adminEmail.hashCode());
		result = prime * result
				+ ((beginStepId == null) ? 0 : beginStepId.hashCode());
		result = prime * result
				+ ((comments == null) ? 0 : comments.hashCode());
		result = prime
				* result
				+ ((globalDeadlineDate == null) ? 0 : globalDeadlineDate
						.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((insertDate == null) ? 0 : insertDate.hashCode());
		result = prime * result
				+ ((insertUser == null) ? 0 : insertUser.hashCode());
		result = prime * result
				+ ((listZoneId == null) ? 0 : listZoneId.hashCode());
//		result = prime * result
//				+ ((managedDataDef == null) ? 0 : managedDataDef.hashCode());
		result = prime * result + ((modDate == null) ? 0 : modDate.hashCode());
		result = prime * result + ((modUser == null) ? 0 : modUser.hashCode());
		result = prime * result
				+ ((processHead == null) ? 0 : processHead.hashCode());
		result = prime * result
				+ ((processorStepId == null) ? 0 : processorStepId.hashCode());
		result = prime * result
				+ ((productionDate == null) ? 0 : productionDate.hashCode());
		result = prime * result
				+ ((productionUser == null) ? 0 : productionUser.hashCode());
		result = prime * result
				+ ((totalTime == null) ? 0 : totalTime.hashCode());
		result = prime * result
				+ ((totalTimeUnit == null) ? 0 : totalTimeUnit.hashCode());
		result = prime * result
				+ ((workZoneId == null) ? 0 : workZoneId.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WProcessDefThin))
			return false;
		WProcessDefThin other = (WProcessDefThin) obj;
		if (active != other.active)
			return false;
		if (additionalZoneId == null) {
			if (other.additionalZoneId != null)
				return false;
		} else if (!additionalZoneId.equals(other.additionalZoneId))
			return false;
		if (adminEmail == null) {
			if (other.adminEmail != null)
				return false;
		} else if (!adminEmail.equals(other.adminEmail))
			return false;
		if (beginStepId == null) {
			if (other.beginStepId != null)
				return false;
		} else if (!beginStepId.equals(other.beginStepId))
			return false;
		if (comments == null) {
			if (other.comments != null)
				return false;
		} else if (!comments.equals(other.comments))
			return false;
		if (globalDeadlineDate == null) {
			if (other.globalDeadlineDate != null)
				return false;
		} else if (!globalDeadlineDate.equals(other.globalDeadlineDate))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (insertDate == null) {
			if (other.insertDate != null)
				return false;
		} else if (!insertDate.equals(other.insertDate))
			return false;
		if (insertUser == null) {
			if (other.insertUser != null)
				return false;
		} else if (!insertUser.equals(other.insertUser))
			return false;
		if (listZoneId == null) {
			if (other.listZoneId != null)
				return false;
		} else if (!listZoneId.equals(other.listZoneId))
			return false;
//		if (managedDataDef == null) {
//			if (other.managedDataDef != null)
//				return false;
//		} else if (!managedDataDef.equals(other.managedDataDef))
//			return false;
		if (modDate == null) {
			if (other.modDate != null)
				return false;
		} else if (!modDate.equals(other.modDate))
			return false;
		if (modUser == null) {
			if (other.modUser != null)
				return false;
		} else if (!modUser.equals(other.modUser))
			return false;
		if (processHead == null) {
			if (other.processHead != null)
				return false;
		} else if (!processHead.equals(other.processHead))
			return false;
		if (processorStepId == null) {
			if (other.processorStepId != null)
				return false;
		} else if (!processorStepId.equals(other.processorStepId))
			return false;
		if (productionDate == null) {
			if (other.productionDate != null)
				return false;
		} else if (!productionDate.equals(other.productionDate))
			return false;
		if (productionUser == null) {
			if (other.productionUser != null)
				return false;
		} else if (!productionUser.equals(other.productionUser))
			return false;
		if (totalTime == null) {
			if (other.totalTime != null)
				return false;
		} else if (!totalTime.equals(other.totalTime))
			return false;
		if (totalTimeUnit == null) {
			if (other.totalTimeUnit != null)
				return false;
		} else if (!totalTimeUnit.equals(other.totalTimeUnit))
			return false;
		if (workZoneId == null) {
			if (other.workZoneId != null)
				return false;
		} else if (!workZoneId.equals(other.workZoneId))
			return false;
		return true;
	}


	@Override
	public String toString() {
		return "WProcessDefThin ["
				+ (id != null ? "id=" + id + ", " : "")
				+ (processHead != null ? "processHead=" + processHead + ", "
						: "")
				+ "active="
				+ active
				+ ", "
				+ (productionDate != null ? "productionDate=" + productionDate
						+ ", " : "")
				+ (productionUser != null ? "productionUser=" + productionUser
						+ ", " : "")
				+ (comments != null ? "comments=" + comments + ", " : "")
				+ (beginStepId != null ? "beginStepId=" + beginStepId + ", "
						: "")
				+ (listZoneId != null ? "listZoneId=" + listZoneId + ", " : "")
				+ (workZoneId != null ? "workZoneId=" + workZoneId + ", " : "")
				+ (additionalZoneId != null ? "additionalZoneId="
						+ additionalZoneId + ", " : "")
				+ (processorStepId != null ? "processorStepId="
						+ processorStepId + ", " : "")
				+ (adminEmail != null ? "adminEmail=" + adminEmail + ", " : "")
				+ (totalTime != null ? "totalTime=" + totalTime + ", " : "")
				+ (totalTimeUnit != null ? "totalTimeUnit=" + totalTimeUnit
						+ ", " : "")
				+ (globalDeadlineDate != null ? "globalDeadlineDate="
						+ globalDeadlineDate + ", " : "")
				+ (insertDate != null ? "insertDate=" + insertDate + ", " : "")
				+ (insertUser != null ? "insertUser=" + insertUser + ", " : "")
				+ (modDate != null ? "modDate=" + modDate + ", " : "")
				+ (modUser != null ? "modUser=" + modUser + ", " : "")
				+ (systemEmailAccount != null ? "systemEmailAccount="
						+ systemEmailAccount + ", " : "")
				+ (arrivingAdminNoticeTemplate != null ? "arrivingAdminNoticeTemplate="
						+ arrivingAdminNoticeTemplate + ", "
						: "")
				+ (arrivingUserNoticeTemplate != null ? "arrivingUserNoticeTemplate="
						+ arrivingUserNoticeTemplate
						: "") + "]";
	}


	public WEmailAccount getSystemEmailAccount() {
		return systemEmailAccount;
	}


	public void setSystemEmailAccount(WEmailAccount systemEmailAccount) {
		this.systemEmailAccount = systemEmailAccount;
	}


	public WEmailTemplates getArrivingAdminNoticeTemplate() {
		return arrivingAdminNoticeTemplate;
	}


	public void setArrivingAdminNoticeTemplate(
			WEmailTemplates arrivingAdminNoticeTemplate) {
		this.arrivingAdminNoticeTemplate = arrivingAdminNoticeTemplate;
	}


	public WEmailTemplates getArrivingUserNoticeTemplate() {
		return arrivingUserNoticeTemplate;
	}


	public void setArrivingUserNoticeTemplate(
			WEmailTemplates arrivingUserNoticeTemplate) {
		this.arrivingUserNoticeTemplate = arrivingUserNoticeTemplate;
	}

	
	// TODO HABRIA Q QUITAR ESTO DE ESTA CLASE ... VER COMENTARIO AL PPIO DE ESTA CLASE en la definicion de las propiedades
	
	
}
