package org.beeblos.bpm.core.model;

// Generated Jul 29, 2013 1:15:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WDataType generated by hbm2java
 */
public class WDataType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private Integer maxLength;
	private String showName;
	private Integer sqlType; // must match with java.sql.Type
	private String sqlTypeName; // must match with java.sql.Type
	private Date insertDate;
	private int insertUser;
	private Date modDate;
	private int modUser;

	public WDataType() {
	}


	public WDataType(String name, Integer maxLength, String showName) {
		this.name = name;
		this.maxLength = maxLength;
		this.showName = showName;

	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getMaxLength() {
		return this.maxLength;
	}

	public void setMaxLength(Integer maxLength) {
		this.maxLength = maxLength;
	}

	public String getShowName() {
		return this.showName;
	}

	public void setShowName(String showName) {
		this.showName = showName;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public int getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(int insertUser) {
		this.insertUser = insertUser;
	}

	public Date getModDate() {
		return this.modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

	public int getModUser() {
		return this.modUser;
	}

	public void setModUser(int modUser) {
		this.modUser = modUser;
	}


	public Integer getSqlType() {
		return sqlType;
	}


	public void setSqlType(Integer sqlType) {
		this.sqlType = sqlType;
	}


	public String getSqlTypeName() {
		return sqlTypeName;
	}


	public void setSqlTypeName(String sqlTypeName) {
		this.sqlTypeName = sqlTypeName;
	}

}
