package org.beeblos.bpm.core.model;

// Generated Jul 29, 2013 1:15:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WDataType generated by hbm2java
 */
public class WDataType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private Integer maxLength;
	private String showName;
	private Integer sqlType; // must match with java.sql.Type
	private String sqlTypeName; // must match with java.sql.Type
	private Date insertDate;
	private Integer insertUser;
	private Date modDate;
	private Integer modUser;

	public WDataType() {
	}


	public WDataType(String name, Integer maxLength, String showName) {
		this.name = name;
		this.maxLength = maxLength;
		this.showName = showName;

	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getMaxLength() {
		return this.maxLength;
	}

	public void setMaxLength(Integer maxLength) {
		this.maxLength = maxLength;
	}

	public String getShowName() {
		return this.showName;
	}

	public void setShowName(String showName) {
		this.showName = showName;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Integer getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(Integer insertUser) {
		this.insertUser = insertUser;
	}

	public Date getModDate() {
		return this.modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

	public Integer getModUser() {
		return this.modUser;
	}

	public void setModUser(Integer modUser) {
		this.modUser = modUser;
	}


	public Integer getSqlType() {
		return sqlType;
	}


	public void setSqlType(Integer sqlType) {
		this.sqlType = sqlType;
	}


	public String getSqlTypeName() {
		return sqlTypeName;
	}


	public void setSqlTypeName(String sqlTypeName) {
		this.sqlTypeName = sqlTypeName;
	}


	@Override
	public String toString() {
		return "WDataType ["
				+ (id != null ? "id=" + id + ", " : "")
				+ (name != null ? "name=" + name + ", " : "")
				+ (maxLength != null ? "maxLength=" + maxLength + ", " : "")
				+ (showName != null ? "showName=" + showName + ", " : "")
				+ (sqlType != null ? "sqlType=" + sqlType + ", " : "")
				+ (sqlTypeName != null ? "sqlTypeName=" + sqlTypeName + ", "
						: "")
				+ (insertDate != null ? "insertDate=" + insertDate + ", " : "")
				+ "insertUser=" + insertUser + ", "
				+ (modDate != null ? "modDate=" + modDate + ", " : "")
				+ "modUser=" + modUser + "]";
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((insertDate == null) ? 0 : insertDate.hashCode());
		result = prime * result + insertUser;
		result = prime * result
				+ ((maxLength == null) ? 0 : maxLength.hashCode());
		result = prime * result + ((modDate == null) ? 0 : modDate.hashCode());
		result = prime * result + modUser;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result
				+ ((showName == null) ? 0 : showName.hashCode());
		result = prime * result + ((sqlType == null) ? 0 : sqlType.hashCode());
		result = prime * result
				+ ((sqlTypeName == null) ? 0 : sqlTypeName.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WDataType))
			return false;
		WDataType other = (WDataType) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (insertDate == null) {
			if (other.insertDate != null)
				return false;
		} else if (!insertDate.equals(other.insertDate))
			return false;
		if (insertUser != other.insertUser)
			return false;
		if (maxLength == null) {
			if (other.maxLength != null)
				return false;
		} else if (!maxLength.equals(other.maxLength))
			return false;
		if (modDate == null) {
			if (other.modDate != null)
				return false;
		} else if (!modDate.equals(other.modDate))
			return false;
		if (modUser != other.modUser)
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (showName == null) {
			if (other.showName != null)
				return false;
		} else if (!showName.equals(other.showName))
			return false;
		if (sqlType == null) {
			if (other.sqlType != null)
				return false;
		} else if (!sqlType.equals(other.sqlType))
			return false;
		if (sqlTypeName == null) {
			if (other.sqlTypeName != null)
				return false;
		} else if (!sqlTypeName.equals(other.sqlTypeName))
			return false;
		return true;
	}
	
}