package org.beeblos.bpm.core.model;

// Generated Jul 29, 2013 1:15:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WProcessDataField generated by hbm2java
 */
public class WProcessDataField implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private WProcessHead processHead;
	private WDataType dataType;
	private String name;
	private Boolean required;
	private String comments;

	// trail
	private Date insertDate;
	private int insertUser;
	private Date modDate;
	private int modUser;

	public WProcessDataField() {
	}

	public WProcessDataField(WProcessHead processHead, WDataType dataType,
			String name, Boolean required, String comments) {
		this.processHead = processHead;
		this.dataType = dataType;
		this.name = name;
		this.required = required;
		this.comments = comments;

	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public WProcessHead getProcessHead() {
		return processHead;
	}

	public void setProcessHead(WProcessHead processHead) {
		this.processHead = processHead;
	}

	public WDataType getDataType() {
		return dataType;
	}

	public void setDataType(WDataType dataType) {
		this.dataType = dataType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getRequired() {
		return this.required;
	}

	public void setRequired(Boolean required) {
		this.required = required;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public int getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(int insertUser) {
		this.insertUser = insertUser;
	}

	public Date getModDate() {
		return this.modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

	public int getModUser() {
		return this.modUser;
	}

	public void setModUser(int modUser) {
		this.modUser = modUser;
	}

}
