package org.beeblos.bpm.core.model;

// Generated Jan 20, 2012 7:08:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WProcessWork generated by hbm2java
 */
public class WProcessWork implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private WProcessStatus status;

	private WProcessDef process;
	@Deprecated
	private int version;
	
	private Date startingTime;
	private Integer startingType;
	private Date endTime;
	private String reference;
	private String comments;
	private Integer insertUser;
	private Date insertDate;
	private Integer modUser;
	private Date modDate;
	private Integer idObject;
	private String idObjectType;

	public WProcessWork() {
		super();
	}
	
	public WProcessWork(boolean createEmtpyObjects ){
		super();
		if ( createEmtpyObjects ) {
			this.status=new WProcessStatus();
			
		}	
	}

	public WProcessWork(WProcessStatus status, WProcessDef process,
			Date startingTime, String reference, Integer insertUser,
			Date insertDate, Integer modUser, Date modDate) {
		this.status = status;
		this.process = process;
		this.startingTime = startingTime;
		this.reference = reference;
		this.insertUser = insertUser;
		this.insertDate = insertDate;
		this.modUser = modUser;
		this.modDate = modDate;
	}

	public WProcessWork(WProcessStatus status, WProcessDef process,
			Date startingTime, Integer startingType, Date endTime,
			String reference, String comments, Integer insertUser, Date insertDate,
			Integer modUser, Date modDate, Integer idObject,
			String idObjectType) {
		this.status = status;
		this.process = process;
		this.startingTime = startingTime;
		this.startingType = startingType;
		this.endTime = endTime;
		this.reference = reference;
		this.comments = comments;
		this.insertUser = insertUser;
		this.insertDate = insertDate;
		this.modUser = modUser;
		this.modDate = modDate;
		this.idObject = idObject;
		this.idObjectType = idObjectType;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Deprecated
	public int getVersion() {
		return this.version;
	}

	@Deprecated
	public void setVersion(int version) {
		this.version = version;
	}

	public WProcessStatus getStatus() {
		return status;
	}

	public void setStatus(WProcessStatus status) {
		this.status = status;
	}

	public WProcessDef getProcess() {
		return process;
	}

	public void setProcess(WProcessDef process) {
		this.process = process;
	}

	public Date getStartingTime() {
		return this.startingTime;
	}

	public void setStartingTime(Date startingTime) {
		this.startingTime = startingTime;
	}

	public Integer getStartingType() {
		return this.startingType;
	}

	public void setStartingType(Integer startingType) {
		this.startingType = startingType;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Integer getInsertUser() {
		return this.insertUser;
	}

	public void setInsertUser(Integer insertUser) {
		this.insertUser = insertUser;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Integer getModUser() {
		return this.modUser;
	}

	public void setModUser(Integer modUser) {
		this.modUser = modUser;
	}

	public Date getModDate() {
		return this.modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

	public Integer getIdObject() {
		return idObject;
	}

	public void setIdObject(Integer idObject) {
		this.idObject = idObject;
	}

	public String getIdObjectType() {
		return idObjectType;
	}

	public void setIdObjectType(String idObjectType) {
		this.idObjectType = idObjectType;
	}

	@Override
	public String toString() {
		return "WProcessWork [id=" + id + ", version=" + version + ", status="
				+ status + ", process=" + process + ", startingTime="
				+ startingTime + ", startingType=" + startingType
				+ ", endTime=" + endTime + ", reference=" + reference
				+ ", comments=" + comments + ", insertUser=" + insertUser
				+ ", insertDate=" + insertDate + ", modUser=" + modUser
				+ ", modDate=" + modDate + ", idObject=" + idObject
				+ ", idObjectType=" + idObjectType + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((comments == null) ? 0 : comments.hashCode());
		result = prime * result + ((endTime == null) ? 0 : endTime.hashCode());
		result = prime * result
				+ ((idObject == null) ? 0 : idObject.hashCode());
		result = prime * result
				+ ((idObjectType == null) ? 0 : idObjectType.hashCode());
		result = prime * result
				+ ((insertDate == null) ? 0 : insertDate.hashCode());
		result = prime * result
				+ ((insertUser == null) ? 0 : insertUser.hashCode());
		result = prime * result + ((modDate == null) ? 0 : modDate.hashCode());
		result = prime * result + ((modUser == null) ? 0 : modUser.hashCode());
		result = prime * result + ((process == null) ? 0 : process.hashCode());
		result = prime * result
				+ ((reference == null) ? 0 : reference.hashCode());
		result = prime * result
				+ ((startingTime == null) ? 0 : startingTime.hashCode());
		result = prime * result
				+ ((startingType == null) ? 0 : startingType.hashCode());
		result = prime * result + ((status == null) ? 0 : status.hashCode());

		result = prime * result + version;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		WProcessWork other = (WProcessWork) obj;
		if (comments == null) {
			if (other.comments != null)
				return false;
		} else if (!comments.equals(other.comments))
			return false;
		if (endTime == null) {
			if (other.endTime != null)
				return false;
		} else if (!endTime.equals(other.endTime))
			return false;
		if (idObject == null) {
			if (other.idObject != null)
				return false;
		} else if (!idObject.equals(other.idObject))
			return false;
		if (idObjectType == null) {
			if (other.idObjectType != null)
				return false;
		} else if (!idObjectType.equals(other.idObjectType))
			return false;
		if (insertDate == null) {
			if (other.insertDate != null)
				return false;
		} else if (!insertDate.equals(other.insertDate))
			return false;
		if (insertUser == null) {
			if (other.insertUser != null)
				return false;
		} else if (!insertUser.equals(other.insertUser))
			return false;
		if (modDate == null) {
			if (other.modDate != null)
				return false;
		} else if (!modDate.equals(other.modDate))
			return false;
		if (modUser == null) {
			if (other.modUser != null)
				return false;
		} else if (!modUser.equals(other.modUser))
			return false;
		if (process == null) {
			if (other.process != null)
				return false;
		} else if (!process.equals(other.process))
			return false;
		if (reference == null) {
			if (other.reference != null)
				return false;
		} else if (!reference.equals(other.reference))
			return false;
		if (startingTime == null) {
			if (other.startingTime != null)
				return false;
		} else if (!startingTime.equals(other.startingTime))
			return false;
		if (startingType == null) {
			if (other.startingType != null)
				return false;
		} else if (!startingType.equals(other.startingType))
			return false;
		if (status == null) {
			if (other.status != null)
				return false;
		} else if (!status.equals(other.status))
			return false;
		if (version != other.version)
			return false;
		return true;
	}

	public boolean empty() {

		if (id!=null && ! id.equals(0)) return false;
		if (version != 0) return false;
		if (status!=null && ! status.empty()) return false;		
		if (reference!=null && ! "".equals(reference)) return false;		
		if (comments!=null && ! "".equals(comments)) return false;
		if (idObject!=null && ! idObject.equals(0)) return false;
		if (idObjectType!=null && ! "".equals(idObjectType)) return false;

		return true;
	}

}
