package org.beeblos.bpm.core.model;

// Generated Jul 29, 2013 1:15:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WProcessDataField generated by hbm2java
 */
public class WStepDataField implements java.io.Serializable {

	/**
	 * this Class manages related fields for a a step
	 * Only must select a step defined in w_process_data_field because
	 * the datafields are managed at process-head level
	 * Used steps can't be deleted from w_process_data_field 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Integer stepHeadId;
	
//	private WStepHead stepHead;
	
	private WProcessDataField dataField;
	private String name;
	private Boolean required;
	private String comments;
	private Boolean active;
	private Integer length;
	private String defaultValue;
	
	// trail
	private Date insertDate;
	private Integer insertUser;
	private Date modDate;
	private Integer modUser;

	public WStepDataField() {
		super();
	}
	
	public WStepDataField(boolean createEmtpyObjects ){
		super();
		if ( createEmtpyObjects ) {

			this.dataField = new WProcessDataField();
		
		}	
	}
	
	public WStepDataField(Integer id, Integer stepHeadId,
			WProcessDataField dataField, String name, Boolean required,
			String comments, Boolean active, Integer length, String defaultValue) {
		this.id = id;
		this.stepHeadId = stepHeadId;
		this.dataField = dataField;
		this.name = name;
		this.required = required;
		this.comments = comments;
		this.active = active;
		this.length = length;
		this.defaultValue = defaultValue;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public WProcessDataField getDataField() {
		return dataField;
	}

	public void setDataField(WProcessDataField dataField) {
		this.dataField = dataField;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getRequired() {
		return required;
	}

	public void setRequired(Boolean required) {
		this.required = required;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Integer getLength() {
		return length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public String getDefaultValue() {
		return defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	public Date getInsertDate() {
		return insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Integer getInsertUser() {
		return insertUser;
	}

	public void setInsertUser(Integer insertUser) {
		this.insertUser = insertUser;
	}

	public Date getModDate() {
		return modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

	public Integer getModUser() {
		return modUser;
	}

	public void setModUser(Integer modUser) {
		this.modUser = modUser;
	}

	public Integer getStepHeadId() {
		return stepHeadId;
	}

	public void setStepHeadId(Integer stepHeadId) {
		this.stepHeadId = stepHeadId;
	}

//	public WStepHead getStepHead() {
//		return stepHead;
//	}
//
//	public void setStepHead(WStepHead stepHead) {
//		this.stepHead = stepHead;
//	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((active == null) ? 0 : active.hashCode());
		result = prime * result
				+ ((comments == null) ? 0 : comments.hashCode());
		result = prime * result
				+ ((dataField == null) ? 0 : dataField.hashCode());
		result = prime * result
				+ ((defaultValue == null) ? 0 : defaultValue.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((insertDate == null) ? 0 : insertDate.hashCode());
		result = prime * result
				+ ((insertUser == null) ? 0 : insertUser.hashCode());
		result = prime * result + ((length == null) ? 0 : length.hashCode());
		result = prime * result + ((modDate == null) ? 0 : modDate.hashCode());
		result = prime * result + ((modUser == null) ? 0 : modUser.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result
				+ ((required == null) ? 0 : required.hashCode());
//		result = prime * result
//				+ ((stepHead == null) ? 0 : stepHead.hashCode());
		result = prime * result
				+ ((stepHeadId == null) ? 0 : stepHeadId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WStepDataField))
			return false;
		WStepDataField other = (WStepDataField) obj;
		if (active == null) {
			if (other.active != null)
				return false;
		} else if (!active.equals(other.active))
			return false;
		if (comments == null) {
			if (other.comments != null)
				return false;
		} else if (!comments.equals(other.comments))
			return false;
		if (dataField == null) {
			if (other.dataField != null)
				return false;
		} else if (!dataField.equals(other.dataField))
			return false;
		if (defaultValue == null) {
			if (other.defaultValue != null)
				return false;
		} else if (!defaultValue.equals(other.defaultValue))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (insertDate == null) {
			if (other.insertDate != null)
				return false;
		} else if (!insertDate.equals(other.insertDate))
			return false;
		if (insertUser == null) {
			if (other.insertUser != null)
				return false;
		} else if (!insertUser.equals(other.insertUser))
			return false;
		if (length == null) {
			if (other.length != null)
				return false;
		} else if (!length.equals(other.length))
			return false;
		if (modDate == null) {
			if (other.modDate != null)
				return false;
		} else if (!modDate.equals(other.modDate))
			return false;
		if (modUser == null) {
			if (other.modUser != null)
				return false;
		} else if (!modUser.equals(other.modUser))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (required == null) {
			if (other.required != null)
				return false;
		} else if (!required.equals(other.required))
			return false;
//		if (stepHead == null) {
//			if (other.stepHead != null)
//				return false;
//		} else if (!stepHead.equals(other.stepHead))
//			return false;
		if (stepHeadId == null) {
			if (other.stepHeadId != null)
				return false;
		} else if (!stepHeadId.equals(other.stepHeadId))
			return false;
		return true;
	}




}
