package org.beeblos.bpm.core.model;

// Generated May 21, 2012 10:49:10 AM by Hibernate Tools 3.4.0.CR1

import org.joda.time.DateTime;

/**
 * SystemObject generated by hbm2java
 */
public class SystemObject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6398244268837946911L;
	private Integer id;
	private String name;
	private String objectClass;
	private Integer hierarchy;
	private String comments;
	private DateTime addDate;
	private Integer addUser;
	private DateTime modDate;
	private Integer modUser;

	public SystemObject() {
	}

	public SystemObject(Integer id, String name, String objectClass, Integer hierarchy,
			String comments, DateTime addDate, Integer addUser, DateTime modDate, Integer modUser) {
		super();
		this.id = id;
		this.name = name;
		this.objectClass = objectClass;
		this.hierarchy = hierarchy;
		this.comments = comments;
		this.addDate = addDate;
		this.addUser = addUser;
		this.modDate = modDate;
		this.modUser = modUser;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getObjectClass() {
		return objectClass;
	}

	public void setObjectClass(String objectClass) {
		this.objectClass = objectClass;
	}

	public Integer getHierarchy() {
		return hierarchy;
	}

	public void setHierarchy(Integer hierarchy) {
		this.hierarchy = hierarchy;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public DateTime getAddDate() {
		return addDate;
	}

	public void setAddDate(DateTime addDate) {
		this.addDate = addDate;
	}

	public Integer getAddUser() {
		return addUser;
	}

	public void setAddUser(Integer addUser) {
		this.addUser = addUser;
	}

	public DateTime getModDate() {
		return modDate;
	}

	public void setModDate(DateTime modDate) {
		this.modDate = modDate;
	}

	public Integer getModUser() {
		return modUser;
	}

	public void setModUser(Integer modUser) {
		this.modUser = modUser;
	}

	@Override
	public String toString() {
		return "SystemObject [id=" + id + ", name=" + name + ", objectClass=" + objectClass
				+ ", hierarchy=" + hierarchy + ", comments=" + comments + ", addDate=" + addDate
				+ ", addUser=" + addUser + ", modDate=" + modDate + ", modUser=" + modUser + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((comments == null) ? 0 : comments.hashCode());
		result = prime * result + ((hierarchy == null) ? 0 : hierarchy.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((objectClass == null) ? 0 : objectClass.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SystemObject other = (SystemObject) obj;
		if (comments == null) {
			if (other.comments != null)
				return false;
		} else if (!comments.equals(other.comments))
			return false;
		if (hierarchy == null) {
			if (other.hierarchy != null)
				return false;
		} else if (!hierarchy.equals(other.hierarchy))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (objectClass == null) {
			if (other.objectClass != null)
				return false;
		} else if (!objectClass.equals(other.objectClass))
			return false;
		return true;
	}

	public boolean empty() {

		if (id != null && !id.equals(0))
			return false;
		if (name != null && !"".equals(name))
			return false;
		if (objectClass != null && !"".equals(objectClass))
			return false;
		if (hierarchy != null && !hierarchy.equals(0))
			return false;
		if (comments != null && !"".equals(comments))
			return false;

		return true;
	}

}
