package org.beeblos.bpm.core.model;

// Generated Oct 30, 2010 12:25:05 AM by Hibernate Tools 3.3.0.GA

import static org.beeblos.bpm.core.util.Constants.EMPTY_OBJECT;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WProcessDef generated by hbm2java
 */
public class WProcessDef implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String comments;
	private WStepDef beginStep;
	
	private String idListZone; // pag que define la lista de seleccion de steps
	private String idWorkZone; // pag que define la zona de trabajo
	private String idAdditionalZone; // pag que define la zona de ayuda ( info adicional )
	
	/*
	 * DESIGN AND TEST TIME FEATURE
	 * At design time the designer can define a list of roles and users that may interact
	 * with the workflow. This info is only to effects to simplify and control the screen
	 * presentation for users and roles that can be assigned to a step or a task ...
	 * 
	 */
	
	// MANY2MANY
	Set<WProcessRole> rolesRelated=new HashSet<WProcessRole>();
	Set<WProcessUser> usersRelated=new HashSet<WProcessUser>();
//	Set<WRoleDef> adminRoles=new HashSet<WRoleDef>();
//	Set<WUserDef> adminUsers=new HashSet<WUserDef>();
	
	
	private Date insertDate;
	private Integer insertUser;
	private Date modDate;
	private Integer modUser;

	public WProcessDef() {
		super();
	}

	
	public WProcessDef(boolean createEmtpyObjects ){
		super();
		if ( createEmtpyObjects ) {
			this.beginStep=new WStepDef( EMPTY_OBJECT );
			
		}	
	}
	
	public WProcessDef(String name, String comments, WStepDef beginStep,
			Date fechaAlta, Date fechaModificacion) {
		this.name = name;
		this.comments = comments;
		this.beginStep = beginStep;
		this.insertDate = fechaAlta;
		this.modDate = fechaModificacion;
	}

	public WProcessDef(String name, String comments, WStepDef beginStep,
			String idListZone, String idWorkZone, String idAdditionalZone,
			Date insertDate, Integer insertUser, Date modDate,
			Integer modUser ) {
		this.name = name;
		this.comments = comments;
		this.beginStep = beginStep;
		this.idListZone = idListZone;
		this.idWorkZone = idWorkZone;
		this.idAdditionalZone = idAdditionalZone;
		this.insertDate = insertDate;
		this.insertUser = insertUser;
		this.modDate = modDate;
		this.modUser = modUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}


	/**
	 * @return the beginStep
	 */
	public WStepDef getBeginStep() {
		return beginStep;
	}

	/**
	 * @param beginStep the beginStep to set
	 */
	public void setBeginStep(WStepDef beginStep) {
		this.beginStep = beginStep;
	}

	public String getIdListZone() {
		return this.idListZone;
	}

	public void setIdListZone(String idListZone) {
		this.idListZone = idListZone;
	}

	public String getIdWorkZone() {
		return this.idWorkZone;
	}

	public void setIdWorkZone(String idWorkZone) {
		this.idWorkZone = idWorkZone;
	}

	public String getIdAdditionalZone() {
		return this.idAdditionalZone;
	}

	public void setIdAdditionalZone(String idAdditionalZone) {
		this.idAdditionalZone = idAdditionalZone;
	}


	
	public Set<WProcessRole> getRolesRelated() {
		return rolesRelated;
	}

	public void setRolesRelated(Set<WProcessRole> rolesRelated) {
		this.rolesRelated = rolesRelated;
	}

	public Set<WProcessUser> getUsersRelated() {
		return usersRelated;
	}

	public void setUsersRelated(Set<WProcessUser> usersRelated) {
		this.usersRelated = usersRelated;
	}



	public Date getInsertDate() {
		return insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Integer getInsertUser() {
		return insertUser;
	}

	public void setInsertUser(Integer insertUser) {
		this.insertUser = insertUser;
	}

	public Date getModDate() {
		return modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

	public Integer getModUser() {
		return modUser;
	}

	public void setModUser(Integer modUser) {
		this.modUser = modUser;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((beginStep == null) ? 0 : beginStep.hashCode());
		result = prime * result
				+ ((comments == null) ? 0 : comments.hashCode());
		result = prime
				* result
				+ ((idAdditionalZone == null) ? 0 : idAdditionalZone.hashCode());
		result = prime * result
				+ ((idListZone == null) ? 0 : idListZone.hashCode());
		result = prime * result
				+ ((idWorkZone == null) ? 0 : idWorkZone.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result
				+ ((rolesRelated == null) ? 0 : rolesRelated.hashCode());
		result = prime * result
				+ ((usersRelated == null) ? 0 : usersRelated.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WProcessDef))
			return false;
		WProcessDef other = (WProcessDef) obj;
		if (beginStep == null) {
			if (other.beginStep != null)
				return false;
		} else if (!beginStep.equals(other.beginStep))
			return false;
		if (comments == null) {
			if (other.comments != null)
				return false;
		} else if (!comments.equals(other.comments))
			return false;
		if (idAdditionalZone == null) {
			if (other.idAdditionalZone != null)
				return false;
		} else if (!idAdditionalZone.equals(other.idAdditionalZone))
			return false;
		if (idListZone == null) {
			if (other.idListZone != null)
				return false;
		} else if (!idListZone.equals(other.idListZone))
			return false;
		if (idWorkZone == null) {
			if (other.idWorkZone != null)
				return false;
		} else if (!idWorkZone.equals(other.idWorkZone))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (rolesRelated == null) {
			if (other.rolesRelated != null)
				return false;
		} else if (!rolesRelated.equals(other.rolesRelated))
			return false;
		if (usersRelated == null) {
			if (other.usersRelated != null)
				return false;
		} else if (!usersRelated.equals(other.usersRelated))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "WProcessDef ["
				+ (id != null ? "id=" + id + ", " : "")
				+ (name != null ? "name=" + name + ", " : "")
				+ (comments != null ? "comments=" + comments + ", " : "")
//				+ (beginStep != null ? "beginStep=" + beginStep + ", " : "")
				+ (idListZone != null ? "idListZone=" + idListZone + ", " : "")
				+ (idWorkZone != null ? "idWorkZone=" + idWorkZone + ", " : "")
				+ (idAdditionalZone != null ? "idAdditionalZone="
						+ idAdditionalZone + ", " : "")
				+ (rolesRelated != null ? "rolesRelated=" + rolesRelated + ", "
						: "")
				+ (usersRelated != null ? "usersRelated=" + usersRelated + ", "
						: "")
				+ (insertDate != null ? "insertDate=" + insertDate + ", " : "")
				+ (insertUser != null ? "insertUser=" + insertUser + ", " : "")
				+ (modDate != null ? "modDate=" + modDate + ", " : "")
				+ (modUser != null ? "modUser=" + modUser : "") + "]";
	}
	

	public boolean empty() {

		if (id!=null && ! id.equals(0)) return false;
		if (name!=null && ! "".equals(name)) return false;
		if (comments!=null && ! "".equals(comments)) return false;
		
		if (beginStep!=null && ! beginStep.empty()) return false;
		
		if (idListZone!=null && ! "".equals(idListZone)) return false;
		if (idWorkZone!=null && ! "".equals(idWorkZone)) return false;
		if (idAdditionalZone!=null && ! "".equals(idAdditionalZone)) return false;
		
		return true;
	}
	
	public void addRole( WRoleDef role, boolean admin, Integer idObject, String idObjectType, Integer insertUser ) {
		WProcessRole wpr = new WProcessRole(admin, idObject, idObjectType, insertUser, new Date() );
		wpr.setProcess(this);
		wpr.setRole(role);
		rolesRelated.add(wpr);
	}
	
	public void addUser( WUserDef user, boolean admin, Integer idObject, String idObjectType, Integer insertUser ) {
		WProcessUser wpu = new WProcessUser(admin, idObject, idObjectType, insertUser, new Date() );
		wpu.setProcess(this);
		wpu.setUser(user);
		usersRelated.add(wpu);
	}

}
