package org.beeblos.bpm.core.model;

// Generated Jul 29, 2013 1:15:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WProcessDataField generated by hbm2java
 */
public class WProcessDataField implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Integer processHeadId;
	private WDataType dataType;
	private String name;
	private Boolean required;
	private String comments;
	private Boolean active;
	private Integer length;
	private boolean nullable=true;
	private boolean unique=false;
	private boolean quoted=false;
	private String defaultValue;
	
	
	// trail
	private Date insertDate;
	private Integer insertUser;
	private Date modDate;
	private Integer modUser;

	public WProcessDataField() {
		super();
	}
	
	public WProcessDataField(boolean createEmtpyObjects ){
		super();
		if ( createEmtpyObjects ) {
			
			this.dataType = new WDataType();
			
		}	
	}

	public WProcessDataField(Integer processHeadId, WDataType dataType,
			String name, Boolean required, String comments, Boolean active, Integer length,
			boolean nullable, boolean unique, boolean quoted, String defaultValue) {
		setProcessHeadId(processHeadId);
		setDataType(dataType);
		setName(name);
		setRequired(required);
		setComments(comments);
		setActive(active);
		setLength(length);
		setNullable(nullable);
		setUnique(unique);
		setQuoted(quoted);
		setDefaultValue(defaultValue);

	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public WDataType getDataType() {
		return dataType;
	}

	public void setDataType(WDataType dataType) {
		this.dataType = dataType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getRequired() {
		return this.required;
	}

	public void setRequired(Boolean required) {
		this.required = required;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}
	
	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Integer getLength() {
		return length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public boolean isNullable() {
		return nullable;
	}

	public void setNullable(boolean nullable) {
		this.nullable = nullable;
	}

	public boolean isUnique() {
		return unique;
	}

	public void setUnique(boolean unique) {
		this.unique = unique;
	}

	public boolean isQuoted() {
		return quoted;
	}

	public void setQuoted(boolean quoted) {
		this.quoted = quoted;
	}

	public String getDefaultValue() {
		return defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Integer getInsertUser() {
		return this.insertUser;
	}

	public Integer getProcessHeadId() {
		return processHeadId;
	}

	public void setProcessHeadId(Integer processHeadId) {
		this.processHeadId = processHeadId;
	}

	public void setInsertUser(Integer insertUser) {
		this.insertUser = insertUser;
	}

	public Date getModDate() {
		return this.modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

	public Integer getModUser() {
		return this.modUser;
	}

	public void setModUser(Integer modUser) {
		this.modUser = modUser;
	}

	@Override
	public String toString() {
		return "WProcessDataField ["
				+ (id != null ? "id=" + id + ", " : "")
				+ (processHeadId != null ? "processHeadId=" + processHeadId
						+ ", " : "")
				+ (dataType != null ? "dataType=" + dataType + ", " : "")
				+ (name != null ? "name=" + name + ", " : "")
				+ (required != null ? "required=" + required + ", " : "")
				+ (comments != null ? "comments=" + comments + ", " : "")
				+ (active != null ? "active=" + active + ", " : "")
				+ (length != null ? "length=" + length + ", " : "")
				+ "nullable="
				+ nullable
				+ ", unique="
				+ unique
				+ ", quoted="
				+ quoted
				+ ", "
				+ (defaultValue != null ? "defaultValue=" + defaultValue + ", "
						: "")
				+ (insertDate != null ? "insertDate=" + insertDate + ", " : "")
				+ (insertUser != null ? "insertUser=" + insertUser + ", " : "")
				+ (modDate != null ? "modDate=" + modDate + ", " : "")
				+ (modUser != null ? "modUser=" + modUser : "") + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((active == null) ? 0 : active.hashCode());
		result = prime * result
				+ ((comments == null) ? 0 : comments.hashCode());
		result = prime * result
				+ ((dataType == null) ? 0 : dataType.hashCode());
		result = prime * result
				+ ((defaultValue == null) ? 0 : defaultValue.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((insertDate == null) ? 0 : insertDate.hashCode());
		result = prime * result
				+ ((insertUser == null) ? 0 : insertUser.hashCode());
		result = prime * result + ((length == null) ? 0 : length.hashCode());
		result = prime * result + ((modDate == null) ? 0 : modDate.hashCode());
		result = prime * result + ((modUser == null) ? 0 : modUser.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + (nullable ? 1231 : 1237);
		result = prime * result
				+ ((processHeadId == null) ? 0 : processHeadId.hashCode());
		result = prime * result + (quoted ? 1231 : 1237);
		result = prime * result
				+ ((required == null) ? 0 : required.hashCode());
		result = prime * result + (unique ? 1231 : 1237);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WProcessDataField))
			return false;
		WProcessDataField other = (WProcessDataField) obj;
		if (active == null) {
			if (other.active != null)
				return false;
		} else if (!active.equals(other.active))
			return false;
		if (comments == null) {
			if (other.comments != null)
				return false;
		} else if (!comments.equals(other.comments))
			return false;
		if (dataType == null) {
			if (other.dataType != null)
				return false;
		} else if (!dataType.equals(other.dataType))
			return false;
		if (defaultValue == null) {
			if (other.defaultValue != null)
				return false;
		} else if (!defaultValue.equals(other.defaultValue))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (insertDate == null) {
			if (other.insertDate != null)
				return false;
		} else if (!insertDate.equals(other.insertDate))
			return false;
		if (insertUser == null) {
			if (other.insertUser != null)
				return false;
		} else if (!insertUser.equals(other.insertUser))
			return false;
		if (length == null) {
			if (other.length != null)
				return false;
		} else if (!length.equals(other.length))
			return false;
		if (modDate == null) {
			if (other.modDate != null)
				return false;
		} else if (!modDate.equals(other.modDate))
			return false;
		if (modUser == null) {
			if (other.modUser != null)
				return false;
		} else if (!modUser.equals(other.modUser))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (nullable != other.nullable)
			return false;
		if (processHeadId == null) {
			if (other.processHeadId != null)
				return false;
		} else if (!processHeadId.equals(other.processHeadId))
			return false;
		if (quoted != other.quoted)
			return false;
		if (required == null) {
			if (other.required != null)
				return false;
		} else if (!required.equals(other.required))
			return false;
		if (unique != other.unique)
			return false;
		return true;
	}

}
