package org.beeblos.bpm.core.model;

//import static org.beeblos.bpm.core.util.Constants.EMPTY_OBJECT;

// Generated Nov 9, 2011 1:15:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * WRoleDef generated by hbm2java
 */
public class WRoleDef implements java.io.Serializable {

	/**
	 * Definition of a role: name, desctiption and eventually an objectType related 
	 * and their id 
	 * 
	 * To know wich users are related with a role you must see w_step_role object ...
	 * w_step_role represents the relation table and if you ask for an user you can
	 * obtain the list of roles belonging to
	 * 
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private String description;
	private Integer idObject;
	private String idObjectType;

	public WRoleDef() {
	}

	public WRoleDef(boolean createEmtpyObjects ){
		super();
//		if ( createEmtpyObjects ) {
			// no objects to create for now ...
//		}	
	}
	
	public WRoleDef(String name) {
		this.name = name;
	}

	public WRoleDef(String name, String description, Integer idObject,
			String idObjectType) {
		this.name = name;
		this.description = description;
		this.idObject = idObject;
		this.idObjectType = idObjectType;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getIdObject() {
		return this.idObject;
	}

	public void setIdObject(Integer idObject) {
		this.idObject = idObject;
	}

	public String getIdObjectType() {
		return this.idObjectType;
	}

	public void setIdObjectType(String idObjectType) {
		this.idObjectType = idObjectType;
	}


	@Override
	public String toString() {
		return "WRoleDef ["
				+ (id != null ? "id=" + id + ", " : "")
				+ (name != null ? "name=" + name + ", " : "")
				+ (description != null ? "description=" + description + ", "
						: "")
				+ (idObject != null ? "idObject=" + idObject + ", " : "")
				+ (idObjectType != null ? "idObjectType=" + idObjectType : "")
				+ "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((description == null) ? 0 : description.hashCode());
		result = prime * result
				+ ((idObject == null) ? 0 : idObject.hashCode());
		result = prime * result
				+ ((idObjectType == null) ? 0 : idObjectType.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WRoleDef))
			return false;
		WRoleDef other = (WRoleDef) obj;
		if (description == null) {
			if (other.description != null)
				return false;
		} else if (!description.equals(other.description))
			return false;
		if (idObject == null) {
			if (other.idObject != null)
				return false;
		} else if (!idObject.equals(other.idObject))
			return false;
		if (idObjectType == null) {
			if (other.idObjectType != null)
				return false;
		} else if (!idObjectType.equals(other.idObjectType))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}		
	

	public boolean empty() {

		if (id!=null && ! id.equals(0)) return false;
		
		if (name!=null && ! "".equals(name)) return false;
		if (description!=null && ! "".equals(description)) return false;
		if (idObject!=null && ! idObject.equals(0)) return false;
		if (idObjectType!=null && ! "".equals(idObjectType)) return false;		
		
		return true;
	}
	
}
