package org.beeblos.bpm.core.model;

// Generated Jul 29, 2013 1:15:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WProcessDataField generated by hbm2java
 */
public class WStepDataField implements java.io.Serializable {

	/**
	 * this Class manages related fields for a a step
	 * Only must select a step defined in w_process_data_field because
	 * the datafields are managed at process-head level
	 * Used steps can't be deleted from w_process_data_field 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Integer stepDefId;
	private WProcessDataField dataField;
	private String name;
	private Boolean required;
	private String comments;
	private Boolean active;
	private Integer length;
	private String defaultValue;
	
	// trail
	private Date insertDate;
	private int insertUser;
	private Date modDate;
	private int modUser;

	public WStepDataField() {
		super();
	}
	
	public WStepDataField(boolean createEmtpyObjects ){
		super();
		if ( createEmtpyObjects ) {

			this.dataField = new WProcessDataField();
		
		}	
	}
	
	public WStepDataField(Integer id, Integer stepDefId,
			WProcessDataField dataField, String name, Boolean required,
			String comments, Boolean active, Integer length, String defaultValue) {
		this.id = id;
		this.stepDefId = stepDefId;
		this.dataField = dataField;
		this.name = name;
		this.required = required;
		this.comments = comments;
		this.active = active;
		this.length = length;
		this.defaultValue = defaultValue;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public WProcessDataField getDataField() {
		return dataField;
	}

	public void setDataField(WProcessDataField dataField) {
		this.dataField = dataField;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getRequired() {
		return required;
	}

	public void setRequired(Boolean required) {
		this.required = required;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Integer getLength() {
		return length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public String getDefaultValue() {
		return defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	public Date getInsertDate() {
		return insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public int getInsertUser() {
		return insertUser;
	}

	public void setInsertUser(int insertUser) {
		this.insertUser = insertUser;
	}

	public Date getModDate() {
		return modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

	public int getModUser() {
		return modUser;
	}

	public void setModUser(int modUser) {
		this.modUser = modUser;
	}

	public Integer getStepDefId() {
		return stepDefId;
	}

	public void setStepDefId(Integer stepDefId) {
		this.stepDefId = stepDefId;
	}


}
