package org.beeblos.bpm.core.model;

// Generated Oct 30, 2010 12:25:05 AM by Hibernate Tools 3.3.0.GA

/**
 * WStepResponsesDef generated by hbm2java
 * 
 * RESPUESTA PARA EL PASO "STEP"
 */
public class WStepResponseDef implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer respOrder;
	private String name;

	public WStepResponseDef() {
		super();
	}

	public WStepResponseDef(Integer respOrder, String name) {
		super();
		this.respOrder = respOrder;
		this.name = name;
	}
	
	public WStepResponseDef(Integer id, Integer respOrder, String name) {
		super();
		this.id = id;
		this.respOrder = respOrder;
		this.name = name;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the respOrder
	 */
	public Integer getRespOrder() {
		return respOrder;
	}

	/**
	 * @param respOrder the respOrder to set
	 */
	public void setRespOrder(Integer respOrder) {
		this.respOrder = respOrder;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result
				+ ((respOrder == null) ? 0 : respOrder.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WStepResponseDef))
			return false;
		WStepResponseDef other = (WStepResponseDef) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (respOrder == null) {
			if (other.respOrder != null)
				return false;
		} else if (!respOrder.equals(other.respOrder))
			return false;
		return true;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "WStepResponseDef [id=" + id + ", name=" + name + ", respOrder="
				+ respOrder + "]";
	}

	public boolean empty() {

		if (id!=null && ! id.equals(0)) return false;
		if (name!=null && ! "".equals(name)) return false;
	
		return true;
	}

}
