package org.beeblos.bpm.core.model;

// Generated Oct 30, 2010 12:25:05 AM by Hibernate Tools 3.3.0.GA

/**
 * WStepSequenceDef generated by hbm2java
 */
public class WStepSequenceDef implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private WProcessDef process;
	private Integer version;
	private WStepDef fromStep;
	private WStepDef toStep;
	private boolean enabled;
	private boolean afterAll;
	private String validResponses; // indicates a list of idResponse comma separated

	public WStepSequenceDef() {
	}





	public WStepSequenceDef(Integer id, WProcessDef process, Integer version,
			WStepDef fromStep, WStepDef toStep, boolean enabled,
			boolean afterAll, String validResponses) {
		super();
		this.id = id;
		this.process = process;
		this.version = version;
		this.fromStep = fromStep;
		this.toStep = toStep;
		this.enabled = enabled;
		this.afterAll = afterAll;
		this.validResponses = validResponses;
	}

	public WStepSequenceDef(WProcessDef process, Integer version,
			WStepDef fromStep, WStepDef toStep, boolean enabled,
			boolean afterAll, String validResponses) {
		super();
	
		this.process = process;
		this.version = version;
		this.fromStep = fromStep;
		this.toStep = toStep;
		this.enabled = enabled;
		this.afterAll = afterAll;
		this.validResponses = validResponses;
	}




	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}



	/**
	 * @return the version
	 */
	public Integer getVersion() {
		return version;
	}



	/**
	 * @param version the version to set
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}



	/**
	 * @return the process
	 */
	public WProcessDef getProcess() {
		return process;
	}



	/**
	 * @param process the process to set
	 */
	public void setProcess(WProcessDef process) {
		this.process = process;
	}



	/**
	 * @return the fromStep
	 */
	public WStepDef getFromStep() {
		return fromStep;
	}



	/**
	 * @param fromStep the fromStep to set
	 */
	public void setFromStep(WStepDef fromStep) {
		this.fromStep = fromStep;
	}



	/**
	 * @return the toStep
	 */
	public WStepDef getToStep() {
		return toStep;
	}



	/**
	 * @param toStep the toStep to set
	 */
	public void setToStep(WStepDef toStep) {
		this.toStep = toStep;
	}






	/**
	 * @return the enabled
	 */
	public boolean isEnabled() {
		return enabled;
	}



	/**
	 * @param enabled the enabled to set
	 */
	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}



	/**
	 * @return the afterAll
	 */
	public boolean isAfterAll() {
		return afterAll;
	}



	/**
	 * @param afterAll the afterAll to set
	 */
	public void setAfterAll(boolean afterAll) {
		this.afterAll = afterAll;
	}



	/**
	 * @return the validResponses
	 */
	public String getValidResponses() {
		return validResponses;
	}



	/**
	 * @param validResponses the validResponses to set
	 */
	public void setValidResponses(String validResponses) {
		this.validResponses = validResponses;
	}



	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (afterAll ? 1231 : 1237);
		result = prime * result + (enabled ? 1231 : 1237);
		result = prime * result
				+ ((fromStep == null) ? 0 : fromStep.hashCode());
		result = prime * result + ((process == null) ? 0 : process.hashCode());
		result = prime * result + ((toStep == null) ? 0 : toStep.hashCode());
		result = prime * result
				+ ((validResponses == null) ? 0 : validResponses.hashCode());
		result = prime * result + ((version == null) ? 0 : version.hashCode());
		return result;
	}



	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WStepSequenceDef))
			return false;
		WStepSequenceDef other = (WStepSequenceDef) obj;
		if (afterAll != other.afterAll)
			return false;
		if (enabled != other.enabled)
			return false;
		if (fromStep == null) {
			if (other.fromStep != null)
				return false;
		} else if (!fromStep.equals(other.fromStep))
			return false;
		if (process == null) {
			if (other.process != null)
				return false;
		} else if (!process.equals(other.process))
			return false;
		if (toStep == null) {
			if (other.toStep != null)
				return false;
		} else if (!toStep.equals(other.toStep))
			return false;
		if (validResponses == null) {
			if (other.validResponses != null)
				return false;
		} else if (!validResponses.equals(other.validResponses))
			return false;
		if (version == null) {
			if (other.version != null)
				return false;
		} else if (!version.equals(other.version))
			return false;
		return true;
	}



	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "WStepSequenceDef [afterAll=" + afterAll + ", enabled="
				+ enabled + ", fromStep=" + fromStep + ", id=" + id
				+ ", process=" + process + ", toStep=" + toStep
				+ ", validResponses=" + validResponses + ", version=" + version
				+ "]";
	}


}
