package org.beeblos.bpm.core.model;

//import static org.beeblos.bpm.core.util.Constants.EMPTY_OBJECT;

// Generated Oct 30, 2010 12:25:05 AM by Hibernate Tools 3.3.0.GA

/**
 * WTimeUnits generated by hbm2java
 */
public class WTimeUnit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private Integer conversion;

	public WTimeUnit() {
		super();
	}

	public WTimeUnit(boolean createEmtpyObjects ){
		super();
		if ( createEmtpyObjects ) {
			
		}	
	}
	public WTimeUnit(String name, Integer conversion) {
		this.name = name;
		this.conversion = conversion;
	}



	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getConversion() {
		return this.conversion;
	}

	public void setConversion(Integer conversion) {
		this.conversion = conversion;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((conversion == null) ? 0 : conversion.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WTimeUnit))
			return false;
		WTimeUnit other = (WTimeUnit) obj;
		if (conversion == null) {
			if (other.conversion != null)
				return false;
		} else if (!conversion.equals(other.conversion))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "WTimeUnit [id=" + id + ", name=" + name + ", conversion="
				+ conversion + "]";
	}

	public boolean empty() {

		if (id!=null && ! id.equals(0)) return false;
		if (name!=null && ! "".equals(name)) return false;
		if (conversion!=null && ! conversion.equals(0)) return false;
		
		return true;
	}
	
	
}
