package org.beeblos.bpm.core.model;

//import static org.beeblos.bpm.core.util.Constants.EMPTY_OBJECT;

// Generated Oct 30, 2010 12:25:05 AM by Hibernate Tools 3.3.0.GA

/**
 * WTimeUnits generated by hbm2java
 */
public class WTimeUnit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private Long conversion;

	public WTimeUnit() {
		super();
	}

	public WTimeUnit(boolean createEmtpyObjects ){
		super();
		if ( createEmtpyObjects ) {
			
		}	
	}
	public WTimeUnit(String name, long conversion) {
		this.name = name;
		this.conversion = conversion;
	}



	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getConversion() {
		return this.conversion;
	}

	public void setConversion(Long conversion) {
		this.conversion = conversion;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(conversion);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WTimeUnit))
			return false;
		WTimeUnit other = (WTimeUnit) obj;
		if (Double.doubleToLongBits(conversion) != Double
				.doubleToLongBits(other.conversion))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "WTimeUnit [conversion=" + conversion + ", id=" + id + ", name="
				+ name + "]";
	}

	public boolean empty() {

		if (id!=null && ! id.equals(0)) return false;
		if (name!=null && ! "".equals(name)) return false;
		if (conversion!=null && ! conversion.equals(0.0)) return false;
		
		return true;
	}
	
	
}
