package org.beeblos.bpm.core.model;


// Generated Nov 9, 2011 1:15:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * WUseridmapper generated by hbm2java
 */
public class WUseridmapper implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idUser;
	private String type;
	private String description;
	private String externalUserId;

	public WUseridmapper() {
	}

	public WUseridmapper(boolean createEmtpyObjects ){
		super();
//		if ( createEmtpyObjects ) {
		// no objects to create for now ...
//		}	
	}




	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getExternalUserId() {
		return this.externalUserId;
	}

	public void setExternalUserId(String externalUserId) {
		this.externalUserId = externalUserId;
	}


	public Integer getIdUser() {
		return idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Override
	public String toString() {
		return "WUseridmapper ["
				+ (idUser != null ? "idUser=" + idUser + ", " : "")
				+ (type != null ? "type=" + type + ", " : "")
				+ (description != null ? "description=" + description + ", "
						: "")
				+ (externalUserId != null ? "externalUserId=" + externalUserId
						: "") + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((description == null) ? 0 : description.hashCode());
		result = prime * result
				+ ((externalUserId == null) ? 0 : externalUserId.hashCode());
		result = prime * result + ((idUser == null) ? 0 : idUser.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WUseridmapper))
			return false;
		WUseridmapper other = (WUseridmapper) obj;
		if (description == null) {
			if (other.description != null)
				return false;
		} else if (!description.equals(other.description))
			return false;
		if (externalUserId == null) {
			if (other.externalUserId != null)
				return false;
		} else if (!externalUserId.equals(other.externalUserId))
			return false;
		if (idUser == null) {
			if (other.idUser != null)
				return false;
		} else if (!idUser.equals(other.idUser))
			return false;
		if (type == null) {
			if (other.type != null)
				return false;
		} else if (!type.equals(other.type))
			return false;
		return true;
	}

	public boolean empty() {

		if (idUser!=null && ! idUser.equals(0)) return false;
		
		if (type!=null && ! "".equals(type)) return false;
		if (description!=null && ! "".equals(description)) return false;
		if (externalUserId!=null && ! "".equals(externalUserId)) return false;		

		return true;
	}

	
}
