package org.beeblos.bpm.core.model;

// Generated Nov 9, 2011 1:15:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WUserRole generated by hbm2java
 * 
 * Indicates the users belonging a role
 */
public class WUserDef implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private String login;
	private String email;
	private boolean active;
	private int insertUser;
	private Date insertDate;
	private Integer modUser;
	private Date modDate;
	private WUseridmapper userMapper;

	public WUserDef() {
		super();
	}
	
	public WUserDef(boolean createEmtpyObjects ){
		super();
		if ( createEmtpyObjects ) {
			this.userMapper=new WUseridmapper();
		}	
	}
	
	public WUserDef(Integer idUser) {
		this.id=idUser;
	}

	public WUserDef(String name, String login, boolean active, int insertUser,
			Date insertDate) {
		this.name=name;
		this.login=login;
		this.active = active;
		this.insertUser = insertUser;
		this.insertDate = insertDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}
	

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public int getInsertUser() {
		return insertUser;
	}

	public void setInsertUser(int insertUser) {
		this.insertUser = insertUser;
	}

	public Date getInsertDate() {
		return insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Integer getModUser() {
		return modUser;
	}

	public void setModUser(Integer modUser) {
		this.modUser = modUser;
	}

	public Date getModDate() {
		return modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

	public WUseridmapper getUserMapper() {
		return userMapper;
	}

	public void setUserMapper(WUseridmapper userMapper) {
		this.userMapper = userMapper;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (active ? 1231 : 1237);
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result
				+ ((insertDate == null) ? 0 : insertDate.hashCode());
		result = prime * result + insertUser;
		result = prime * result + ((login == null) ? 0 : login.hashCode());
		result = prime * result + ((modDate == null) ? 0 : modDate.hashCode());
		result = prime * result + ((modUser == null) ? 0 : modUser.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result
				+ ((userMapper == null) ? 0 : userMapper.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		WUserDef other = (WUserDef) obj;
		if (active != other.active)
			return false;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (insertDate == null) {
			if (other.insertDate != null)
				return false;
		} else if (!insertDate.equals(other.insertDate))
			return false;
		if (insertUser != other.insertUser)
			return false;
		if (login == null) {
			if (other.login != null)
				return false;
		} else if (!login.equals(other.login))
			return false;
		if (modDate == null) {
			if (other.modDate != null)
				return false;
		} else if (!modDate.equals(other.modDate))
			return false;
		if (modUser == null) {
			if (other.modUser != null)
				return false;
		} else if (!modUser.equals(other.modUser))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (userMapper == null) {
			if (other.userMapper != null)
				return false;
		} else if (!userMapper.equals(other.userMapper))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "WUserDef [id=" + id + ", name=" + name + ", login=" + login
				+ ", email=" + email + ", active=" + active + ", insertUser="
				+ insertUser + ", insertDate=" + insertDate + ", modUser="
				+ modUser + ", modDate=" + modDate + ", userMapper="
				+ userMapper + "]";
	}

	public boolean empty() {

		if (id!=null && ! id.equals(0)) return false;
		if (name!=null && ! "".equals(name)) return false;
		if (login!=null && ! "".equals(login)) return false;
		
		return true;
	}
	
	
}
