package org.beeblos.bpm.core.model;

import static org.beeblos.bpm.core.util.Constants.EMPTY_OBJECT;

import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

// Generated Oct 30, 2010 12:25:05 AM by Hibernate Tools 3.3.0.GA

/**
 * WStepSequenceDef generated by hbm2java
 */
public class WStepSequenceDef implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private WProcessDef process; // refers directly a version of the process
	private String name;
	
	// nes 20130913
	private Integer order; // to order sequences (principally for evaluation purpose)
	
	private WStepDef fromStep;
	private WStepDef toStep;
	
	private boolean enabled;
	private boolean afterAll;
	private boolean deleted; // dml 20130829 - si se intenta borrar y tiene "w_step_work_sequence" asociados se marca como deleted para hacer PURGE en caso de que este activo (SOLO DESARROLLO)
	
	private String validResponses; // indicates a list of idResponse comma separated
	
	// dml 20130727
	private String rules;

	/**
	 * nes 20140207
	 * External methods allowed to be executed or invoked by this process
	 * Designer/Programmer responsibility to allow context class and method reachable
	 * at execution time 
	 * Invoking external method must be linked with sequence (routes), step (before
	 * load step, after executing step), process (at start time or at end process time), etc. 
	 * 
	 */
	Set<WExternalMethod> externalMethod = new HashSet<WExternalMethod>(0);
	
	private Integer insertUser;
	private Date insertDate;
	private Integer modUser;
	private Date modDate;

	public WStepSequenceDef() {
	}


	public WStepSequenceDef(boolean createEmtpyObjects ){
		super();
		if ( createEmtpyObjects ) {
			this.process = new WProcessDef( EMPTY_OBJECT );
			this.fromStep = new WStepDef( EMPTY_OBJECT );
			this.toStep = new WStepDef( EMPTY_OBJECT );
			
		}	
	}

	/**
	 * Creates a new StepSequence def (route) beginning in fromStep and ending in toStep
	 * 
	 * @param id
	 * @param process
	 * @param order
	 * @param fromStep
	 * @param toStep
	 * @param enabled
	 * @param afterAll
	 * @param deleted
	 * @param validResponses
	 * @param name
	 */
	public WStepSequenceDef(Integer id, WProcessDef process, Integer order,
			WStepDef fromStep, WStepDef toStep, boolean enabled,
			boolean afterAll, boolean deleted, String validResponses, String name) {
		super();
		this.id = id;
		this.process = process;
		this.order = order;
		this.fromStep = fromStep;
		this.toStep = toStep;
		this.enabled = enabled;
		this.afterAll = afterAll;
		this.deleted = deleted;
		this.validResponses = validResponses;
		this.name = name;
	}

	public WStepSequenceDef(WProcessDef process, Integer order,
			WStepDef fromStep, WStepDef toStep, boolean enabled,
			boolean afterAll, boolean deleted, String validResponses, String name) {
		super();
	
		this.process = process;
		this.order = order;
		this.fromStep = fromStep;
		this.toStep = toStep;
		this.enabled = enabled;
		this.afterAll = afterAll;
		this.deleted = deleted;
		this.validResponses = validResponses;
		this.name = name;
	}

	public WStepSequenceDef(Integer id) {
		super();
		this.id = id;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public Integer getOrder() {
		return order;
	}


	public void setOrder(Integer order) {
		this.order = order;
	}


	/**
	 * @return the process
	 */
	public WProcessDef getProcess() {
		return process;
	}



	/**
	 * @param process the process to set
	 */
	public void setProcess(WProcessDef process) {
		this.process = process;
	}



	/**
	 * @return the fromStep
	 */
	public WStepDef getFromStep() {
		return fromStep;
	}



	/**
	 * @param fromStep the fromStep to set
	 */
	public void setFromStep(WStepDef fromStep) {
		this.fromStep = fromStep;
	}



	/**
	 * @return the toStep
	 */
	public WStepDef getToStep() {
		return toStep;
	}



	/**
	 * @param toStep the toStep to set
	 */
	public void setToStep(WStepDef toStep) {
		this.toStep = toStep;
	}






	/**
	 * @return the enabled
	 */
	public boolean isEnabled() {
		return enabled;
	}



	/**
	 * @param enabled the enabled to set
	 */
	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}



	/**
	 * @return the afterAll
	 */
	public boolean isAfterAll() {
		return afterAll;
	}



	/**
	 * @param afterAll the afterAll to set
	 */
	public void setAfterAll(boolean afterAll) {
		this.afterAll = afterAll;
	}



	public boolean isDeleted() {
		return deleted;
	}


	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}


	/**
	 * @return the validResponses
	 */
	public String getValidResponses() {
		return validResponses;
	}



	/**
	 * @param validResponses the validResponses to set
	 */
	public void setValidResponses(String validResponses) {
		this.validResponses = validResponses;
	}



	public Set<WExternalMethod> getExternalMethod() {
		return externalMethod;
	}


	public void setExternalMethod(Set<WExternalMethod> externalMethod) {
		this.externalMethod = externalMethod;
	}


	public String getRules() {
		return rules;
	}


	public void setRules(String rules) {
		this.rules = rules;
	}


	public Integer getInsertUser() {
		return insertUser;
	}


	public void setInsertUser(Integer insertUser) {
		this.insertUser = insertUser;
	}


	public Date getInsertDate() {
		return insertDate;
	}


	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}


	public Integer getModUser() {
		return modUser;
	}


	public void setModUser(Integer modUser) {
		this.modUser = modUser;
	}


	public Date getModDate() {
		return modDate;
	}


	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (afterAll ? 1231 : 1237);
		result = prime * result + (deleted ? 1231 : 1237);
		result = prime * result + (enabled ? 1231 : 1237);
		result = prime * result
				+ ((externalMethod == null) ? 0 : externalMethod.hashCode());
		result = prime * result
				+ ((fromStep == null) ? 0 : fromStep.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((insertDate == null) ? 0 : insertDate.hashCode());
		result = prime * result
				+ ((insertUser == null) ? 0 : insertUser.hashCode());
		result = prime * result + ((modDate == null) ? 0 : modDate.hashCode());
		result = prime * result + ((modUser == null) ? 0 : modUser.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((order == null) ? 0 : order.hashCode());
		result = prime * result + ((process == null) ? 0 : process.hashCode());
		result = prime * result + ((rules == null) ? 0 : rules.hashCode());
		result = prime * result + ((toStep == null) ? 0 : toStep.hashCode());
		result = prime * result
				+ ((validResponses == null) ? 0 : validResponses.hashCode());
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof WStepSequenceDef))
			return false;
		WStepSequenceDef other = (WStepSequenceDef) obj;
		if (afterAll != other.afterAll)
			return false;
		if (deleted != other.deleted)
			return false;
		if (enabled != other.enabled)
			return false;
		if (externalMethod == null) {
			if (other.externalMethod != null)
				return false;
		} else if (!externalMethod.equals(other.externalMethod))
			return false;
		if (fromStep == null) {
			if (other.fromStep != null)
				return false;
		} else if (!fromStep.equals(other.fromStep))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (insertDate == null) {
			if (other.insertDate != null)
				return false;
		} else if (!insertDate.equals(other.insertDate))
			return false;
		if (insertUser == null) {
			if (other.insertUser != null)
				return false;
		} else if (!insertUser.equals(other.insertUser))
			return false;
		if (modDate == null) {
			if (other.modDate != null)
				return false;
		} else if (!modDate.equals(other.modDate))
			return false;
		if (modUser == null) {
			if (other.modUser != null)
				return false;
		} else if (!modUser.equals(other.modUser))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (order == null) {
			if (other.order != null)
				return false;
		} else if (!order.equals(other.order))
			return false;
		if (process == null) {
			if (other.process != null)
				return false;
		} else if (!process.equals(other.process))
			return false;
		if (rules == null) {
			if (other.rules != null)
				return false;
		} else if (!rules.equals(other.rules))
			return false;
		if (toStep == null) {
			if (other.toStep != null)
				return false;
		} else if (!toStep.equals(other.toStep))
			return false;
		if (validResponses == null) {
			if (other.validResponses != null)
				return false;
		} else if (!validResponses.equals(other.validResponses))
			return false;
		return true;
	}



	@Override
	public String toString() {
		final int maxLen = 2;
		return "WStepSequenceDef ["
				+ (id != null ? "id=" + id + ", " : "")
				+ (process != null ? "process=" + process + ", " : "")
				+ (name != null ? "name=" + name + ", " : "")
				+ (order != null ? "order=" + order + ", " : "")
				+ (fromStep != null ? "fromStep=" + fromStep + ", " : "")
				+ (toStep != null ? "toStep=" + toStep + ", " : "")
				+ "enabled="
				+ enabled
				+ ", afterAll="
				+ afterAll
				+ ", deleted="
				+ deleted
				+ ", "
				+ (validResponses != null ? "validResponses=" + validResponses
						+ ", " : "")
				+ (rules != null ? "rules=" + rules + ", " : "")
				+ (externalMethod != null ? "externalMethod="
						+ toString(externalMethod, maxLen) + ", " : "")
				+ (insertUser != null ? "insertUser=" + insertUser + ", " : "")
				+ (insertDate != null ? "insertDate=" + insertDate + ", " : "")
				+ (modUser != null ? "modUser=" + modUser + ", " : "")
				+ (modDate != null ? "modDate=" + modDate : "") + "]";
	}


	private String toString(Collection<?> collection, int maxLen) {
		StringBuilder builder = new StringBuilder();
		builder.append("[");
		int i = 0;
		for (Iterator<?> iterator = collection.iterator(); iterator.hasNext()
				&& i < maxLen; i++) {
			if (i > 0)
				builder.append(", ");
			builder.append(iterator.next());
		}
		builder.append("]");
		return builder.toString();
	}


}
