package org.beeblos.bpm.core.model;

// Generated Nov 9, 2011 1:15:47 PM by Hibernate Tools 3.4.0.CR1

import org.joda.time.DateTime;

/**
 * WProcessRole generated by hbm2java
 */
public class WProcessRole implements java.io.Serializable, WRoleCol {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private WProcessDef process;
	private WRoleDef role;
	private boolean admin;
	private Integer idObject;
	private String idObjectType;
	private Integer insertUser;
	private DateTime insertDate;

	public WProcessRole() {
	}



	public WProcessRole(boolean admin, Integer idObject, String idObjectType, 
			Integer insertUser, DateTime insertDate) {
		this.admin = admin;
		this.idObject = idObject;
		this.idObjectType = idObjectType;
		this.insertUser = insertUser;
		this.insertDate = insertDate;
	}




	public WProcessDef getProcess() {
		return process;
	}



	public void setProcess(WProcessDef process) {
		this.process = process;
	}



	/* (non-Javadoc)
	 * @see org.beeblos.bpm.core.model.WRoleCol#getRole()
	 */
	@Override
	public WRoleDef getRole() {
		return role;
	}



	/* (non-Javadoc)
	 * @see org.beeblos.bpm.core.model.WRoleCol#setRole(org.beeblos.bpm.core.model.WRoleDef)
	 */
	@Override
	public void setRole(WRoleDef role) {
		this.role = role;
	}



	/* (non-Javadoc)
	 * @see org.beeblos.bpm.core.model.WRoleCol#isAdmin()
	 */
	@Override
	public boolean isAdmin() {
		return admin;
	}



	/* (non-Javadoc)
	 * @see org.beeblos.bpm.core.model.WRoleCol#setAdmin(boolean)
	 */
	@Override
	public void setAdmin(boolean admin) {
		this.admin = admin;
	}



	/* (non-Javadoc)
	 * @see org.beeblos.bpm.core.model.WRoleCol#getIdObject()
	 */
	@Override
	public Integer getIdObject() {
		return idObject;
	}



	/* (non-Javadoc)
	 * @see org.beeblos.bpm.core.model.WRoleCol#setIdObject(java.lang.Integer)
	 */
	@Override
	public void setIdObject(Integer idObject) {
		this.idObject = idObject;
	}



	/* (non-Javadoc)
	 * @see org.beeblos.bpm.core.model.WRoleCol#getIdObjectType()
	 */
	@Override
	public String getIdObjectType() {
		return idObjectType;
	}



	/* (non-Javadoc)
	 * @see org.beeblos.bpm.core.model.WRoleCol#setIdObjectType(java.lang.String)
	 */
	@Override
	public void setIdObjectType(String idObjectType) {
		this.idObjectType = idObjectType;
	}



	/* (non-Javadoc)
	 * @see org.beeblos.bpm.core.model.WRoleCol#getInsertUser()
	 */
	@Override
	public Integer getInsertUser() {
		return this.insertUser;
	}

	/* (non-Javadoc)
	 * @see org.beeblos.bpm.core.model.WRoleCol#setInsertUser(java.lang.Integer)
	 */
	@Override
	public void setInsertUser(Integer insertUser) {
		this.insertUser = insertUser;
	}

	/* (non-Javadoc)
	 * @see org.beeblos.bpm.core.model.WRoleCol#getInsertDate()
	 */
	@Override
	public DateTime getInsertDate() {
		return this.insertDate;
	}

	/* (non-Javadoc)
	 * @see org.beeblos.bpm.core.model.WRoleCol#setInsertDate(org.joda.time.DateTime)
	 */
	@Override
	public void setInsertDate(DateTime insertDate) {
		this.insertDate = insertDate;
	}

}
